package org.fao.fi.services.factsheet.client;

/**
 * FactsheetClientException is a RuntimeException
 * 
 * To avoid loads of try catches in the code, FactsheetClientException is a runtime
 * exception. This assumes however that all code is very well unit tested!
 * 
 * 
 * @author Erik van Ingen
 */

class FactsheetClientException extends RuntimeException {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 590457791260365759L;

	public FactsheetClientException(Throwable e) {
		super(e);
	}

	public FactsheetClientException(String newMessage) {
		super(newMessage);
	}

	public FactsheetClientException(String msg, Throwable e) {
		super(msg, e);
	}

}
