package org.fao.fi.factsheetwebservice;

/**
 * FactsheetException is a RuntimeException
 * 
 * To avoid loads of try catches in the code, FactsheetException is a runtime exception. This assumes however that all
 * code is very well unit tested!
 * 
 * 
 * @author Erik van Ingen
 */

public class FactsheetException extends RuntimeException {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 590457791260365759L;

	public FactsheetException(Throwable e) {
		super(e);
	}

	public FactsheetException(String newMessage) {
		super(newMessage);
	}

	public FactsheetException(String msg, Throwable e) {
		super(msg, e);
	}

}
