package org.fao.fi.commons;

/**
 * FigisException is a RuntimeException
 * 
 * To avoid loads of try catches in the code, FigisException is a runtime exception. This assumes however that all code
 * is very well unit tested!
 * 
 * 
 * @author Erik van Ingen
 */

public class FigisException extends RuntimeException {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 590457791260365759L;

	public FigisException(Throwable e) {
		super(e);
	}

	public FigisException(String newMessage) {
		super(newMessage);
	}

	public FigisException(String msg, Throwable e) {
		super(msg, e);
	}

}
